title: Yaoyao Liu
position: Ph.D. Candidate
affiliation: Max Planck Institute for Informatics
email: yaoyao.liu (at) mpi-inf.mpg.de
keywords: yaoyao liu, liu yaoyao, yaoyaoliu, liuyaoyao
google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/liuyaoyao/
avatar: https://images.yyliu.net/avatar.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Yaoyao Liu is a Ph.D. candidate in Computer Science at Max Planck Institute for Informatics, working with Prof. Bernt Schiele and Prof. Qianru Sun. His research lies in few-shot learning, meta learning, continual learning, and image generation.
canonical: https://www.mpi-inf.mpg.de/~yaliu/
remote_theme: yaoyao-liu/minimal-light
